import { IconDefinition } from '@ant-design/icons-angular';
import {
  AppstoreOutline,
  UsbOutline,
  SoundOutline,
  SettingOutline,
  PushpinOutline,
  PushpinFill,
  EditOutline,
  LaptopOutline,
  DownOutline,
  ImportOutline,
  LinkOutline,
  SwapOutline,
  CheckCircleFill,
  UploadOutline,
  ReloadOutline,
  SaveOutline,
  PlayCircleOutline,
  StopOutline,
  DisconnectOutline,
} from '@ant-design/icons-angular/icons';

export const APP_ICONS: IconDefinition[] = [
  AppstoreOutline,
  UsbOutline,
  SoundOutline,
  SettingOutline,
  PushpinOutline,
  PushpinFill,
  EditOutline,
  LaptopOutline,
  DownOutline,
  ImportOutline,
  LinkOutline,
  SwapOutline,
  CheckCircleFill,
  UploadOutline,
  ReloadOutline,
  SaveOutline,
  PlayCircleOutline,
  StopOutline,
  DisconnectOutline,
];
